"""Lazy public export map for the BeeStack package."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES: dict[str, str] = {
    "Action": "beestack.contracts",
    "AntennalMovementSummary": "beestack.brain",
    "AtlasDownloadRecord": "beestack.brain",
    "AtlasInventory": "beestack.brain",
    "BeeAgent": "beestack.swarm",
    "BeeBodyCalibrationSummary": "beestack.body",
    "BeeBodyPlanArtifact": "beestack.body",
    "BeeBrainActivitySummary": "beestack.brain",
    "BeeBrainAnatomySummary": "beestack.brain",
    "BeeBrainAtlasAsset": "beestack.brain",
    "BeeBrainDataCompletenessPanel": "beestack.visualization",
    "BeeBrainEmpiricalProfile": "beestack.brain",
    "BeeBrainEndToEndReport": "beestack.brain",
    "BeeBrainSourceGap": "beestack.brain",
    "BeeBrainSourceStatus": "beestack.brain",
    "BeeStackConfig": "beestack.config",
    "BeehaveColonySummary": "beestack.swarm",
    "BeliefState": "beestack.mind",
    "BodyState": "beestack.body",
    "BodyTelemetry": "beestack.body",
    "BrainState": "beestack.brain",
    "CalciumImagingProtocol": "beestack.brain",
    "CombGrid": "beestack.niche",
    "CombMetrics": "beestack.niche",
    "DanceVector": "beestack.brain",
    "DataQualityCheck": "beestack.brain",
    "DiagnosticRecord": "beestack.integrity",
    "DigitalTwinReadinessReview": "beestack.digital_twin",
    "DocumentationAudit": "beestack.documentation_audit",
    "EVIDENCE_AVAILABILITY_STATES": "beestack.research",
    "EmpiricalAnatomyDataset": "beestack.brain",
    "EmpiricalBrainDataset": "beestack.brain",
    "EmpiricalCalciumDataset": "beestack.brain",
    "EmpiricalConfig": "beestack.config",
    "EmpiricalEvidenceRecord": "beestack.research",
    "EmpiricalOdorResponsePanel": "beestack.brain",
    "EmpiricalPanelStats": "beestack.brain",
    "EmpiricalTemplateBank": "beestack.brain",
    "EmpiricalWaggleFollowerDataset": "beestack.brain",
    "EvidenceTier": "beestack.digital_twin",
    "FigureAudit": "beestack.figure_audit",
    "FlyBodyBeeBackend": "beestack.body",
    "FlyBodyConfig": "beestack.config",
    "FlyBodyContactMetrics": "beestack.body",
    "FlyBodyModificationPlan": "beestack.body",
    "FlyBodySceneArtifact": "beestack.body",
    "FlyBodySceneRenderConfig": "beestack.body",
    "FollowerOrientationDiagnostics": "beestack.brain",
    "GeneratedReportAudit": "beestack.generated_report_audit",
    "GlomerularResponseSummary": "beestack.brain",
    "HoneybeeCalibrationTarget": "beestack.body",
    "ManuscriptEvidenceLink": "beestack.research",
    "MethodsAnalysisReport": "beestack.research",
    "ModuleIntegrityReport": "beestack.integrity",
    "ModuleMethodScorecard": "beestack.research",
    "ModuleMethodsPanel": "beestack.research",
    "ModuleSynthesisPanel": "beestack.research",
    "ModuleValidationPanel": "beestack.research",
    "ModuleVisualizationPanel": "beestack.research",
    "NeuropilAbbreviation": "beestack.brain",
    "NicheAdapterSummary": "beestack.niche",
    "Observation": "beestack.contracts",
    "PheromoneField": "beestack.swarm",
    "PolicyCandidate": "beestack.mind",
    "PolicySelectionDiagnostics": "beestack.mind",
    "ResearchConfig": "beestack.config",
    "ResearchSuiteReport": "beestack.research",
    "ResearchValidationRecord": "beestack.research",
    "ScaleReadiness": "beestack.digital_twin",
    "ScenarioSweepPanel": "beestack.research",
    "SecurityPostureAudit": "beestack.security.posture",
    "SensitivitySweepResult": "beestack.research",
    "SimulationResult": "beestack.orchestrator",
    "SimulationState": "beestack.orchestrator",
    "SourceAudit": "beestack.source_audit",
    "SparseCode": "beestack.brain",
    "StackContract": "beestack.contracts",
    "StackIntegrityReview": "beestack.integrity",
    "StackSynthesisReview": "beestack.research",
    "TwinReadinessAxis": "beestack.digital_twin",
    "TwinScale": "beestack.digital_twin",
    "ValidationRecord": "beestack.integrity",
    "VisualizationArtifactRecord": "beestack.research",
    "VisualizationConfig": "beestack.config",
    "WaggleDanceKinematics": "beestack.brain",
    "WaggleDanceVisualizationConfig": "beestack.visualization",
    "WaggleDecodingDiagnostics": "beestack.brain",
    "WaggleFollowerSummary": "beestack.visualization",
    "WaggleFollowerTrack": "beestack.brain",
    "action_schema": "beestack.contracts",
    "action_to_flybody_action": "beestack.body",
    "action_to_flybody_named_action": "beestack.body",
    "activity_summary_from_components": "beestack.brain",
    "adapter_smoke_rollout": "beestack.body",
    "all_checks_passed": "beestack.brain",
    "allocate_tasks": "beestack.swarm",
    "analyze_odor_panel": "beestack.brain",
    "antennal_vibration_from_movement": "beestack.brain",
    "assemble_methods_analysis_report": "beestack.research",
    "assemble_research_suite_report": "beestack.research",
    "assemble_stack_synthesis_review": "beestack.research",
    "assess_digital_twin_readiness": "beestack.digital_twin",
    "atlas_download_record_from_asset": "beestack.brain",
    "atlas_download_records_from_dicts": "beestack.brain",
    "atlas_inventories_from_directory": "beestack.brain",
    "atlas_inventory_from_zip": "beestack.brain",
    "audit_documentation": "beestack.documentation_audit",
    "audit_security_posture": "beestack.security.posture",
    "audit_figures": "beestack.figure_audit",
    "audit_generated_reports": "beestack.generated_report_audit",
    "audit_sources": "beestack.source_audit",
    "bee_body_calibration_summary": "beestack.body",
    "bee_brain_data_completeness_panel": "beestack.brain",
    "bee_flight_cycle_action": "beestack.body",
    "bee_walk_cycle_action": "beestack.body",
    "beehave_colony_summary": "beestack.swarm",
    "broadcast_dance": "beestack.swarm",
    "build_empirical_template_bank": "beestack.brain",
    "build_flybody_modification_plan": "beestack.body",
    "calcium_dataset_from_trial_array": "beestack.brain",
    "caste_prior": "beestack.mind",
    "comb_metrics": "beestack.niche",
    "config_from_mapping": "beestack.config",
    "contract_matrix": "beestack.contracts",
    "cost_of_transport": "beestack.body",
    "dance_recruitment_diagnostics": "beestack.swarm",
    "dataset_by_id": "beestack.brain",
    "datasets_for_module": "beestack.brain",
    "decode_waggle": "beestack.brain",
    "digital_twin_axis_catalog": "beestack.digital_twin",
    "digital_twin_readiness_markdown": "beestack.digital_twin",
    "documentation_audit_markdown": "beestack.documentation_audit",
    "dominant_caste": "beestack.mind",
    "empirical_anatomy_datasets": "beestack.brain",
    "empirical_brain_datasets": "beestack.brain",
    "empirical_brain_profile": "beestack.brain",
    "empty_comb": "beestack.niche",
    "extract_pandoc_citation_keys": "beestack.source_audit",
    "finalize_project_outputs": "beestack.documentation_signpost",
    "flybody_action_dim_from_env": "beestack.body",
    "flybody_action_names_from_spec": "beestack.body",
    "flybody_contact_report_markdown": "beestack.body",
    "generated_report_audit_markdown": "beestack.generated_report_audit",
    "heading_estimate_deg": "beestack.brain",
    "hexagonal_packing_score": "beestack.niche",
    "honeybee_calibration_targets": "beestack.body",
    "honeybee_standard_brain_assets": "beestack.brain",
    "integrity_review_markdown": "beestack.integrity",
    "kc_class_counts": "beestack.brain",
    "load_neuropil_abbreviations": "beestack.brain",
    "manuscript_figure_index": "beestack.research",
    "manuscript_figure_index_markdown": "beestack.research",
    "metabolic_budget_j": "beestack.body",
    "methods_analysis_markdown": "beestack.research",
    "model_card": "beestack.manifest",
    "module_coverage": "beestack.manifest",
    "morphology_summary": "beestack.body",
    "neuropil_abbreviations_from_html": "beestack.brain",
    "niche_adapter_summary": "beestack.niche",
    "observation_schema": "beestack.contracts",
    "odor_panel_sparseness": "beestack.brain",
    "parse_bibtex_entries": "beestack.source_audit",
    "parse_paoli_matlab_payload": "beestack.brain",
    "parse_tabular_odor_response_rows": "beestack.brain",
    "pheromone_gradient": "beestack.swarm",
    "policy_selection_diagnostics": "beestack.mind",
    "process_observation": "beestack.brain",
    "render_flybody_long_waggle_scene": "beestack.body",
    "render_flybody_swarm_collision_scene": "beestack.body",
    "render_flybody_waggle_scene": "beestack.body",
    "research_report_markdown": "beestack.research",
    "response_templates_from_calcium_dataset": "beestack.brain",
    "response_templates_from_odor_panel": "beestack.brain",
    "run_sensitivity_sweeps": "beestack.research",
    "run_simulation": "beestack.orchestrator",
    "security_posture_markdown": "beestack.security.posture",
    "signposted_directories": "beestack.documentation_audit",
    "source_audit_markdown": "beestack.source_audit",
    "stack_contracts": "beestack.contracts",
    "stack_integrity_review": "beestack.integrity",
    "stack_synthesis_markdown": "beestack.research",
    "step_body": "beestack.body",
    "summarize_anatomy": "beestack.brain",
    "summarize_antennal_movement_rows": "beestack.brain",
    "summarize_calcium_trials": "beestack.brain",
    "summarize_waggle_follower_rows": "beestack.brain",
    "task_allocation_snapshot": "beestack.orchestrator",
    "template_alignment_matrix": "beestack.brain",
    "thermal_step": "beestack.niche",
    "validate_bee_body_plan_xml": "beestack.body",
    "validate_calcium_dataset": "beestack.brain",
    "validate_config": "beestack.config",
    "validate_diagnostic_payload": "beestack.integrity",
    "validate_download_url": "beestack.security.url_policy",
    "validate_odor_panel": "beestack.brain",
    "validate_rendered_frames": "beestack.body",
    "validate_stack_contracts": "beestack.contracts",
    "waggle_dance_visualization_config": "beestack.visualization",
    "waggle_decoding_diagnostics": "beestack.brain",
    "waggle_kinematics_from_config": "beestack.brain",
    "waggle_vibration_from_followers": "beestack.brain",
    "wing_power_mw": "beestack.body",
    "write_modified_bee_body_plan": "beestack.body",
    "write_prefixed_multi_bee_scene_xml": "beestack.body",
    "zero_action": "beestack.contracts",
    "zero_observation": "beestack.contracts",
}

_LEGACY_EXPORT_NAMES = [
    "Action",
    "AntennalMovementSummary",
    "AtlasDownloadRecord",
    "AtlasInventory",
    "BeeAgent",
    "BeeBodyCalibrationSummary",
    "BeeBodyPlanArtifact",
    "BeeBrainActivitySummary",
    "BeeBrainAnatomySummary",
    "BeeBrainAtlasAsset",
    "BeeBrainDataCompletenessPanel",
    "BeeBrainEmpiricalProfile",
    "BeeBrainEndToEndReport",
    "BeeBrainSourceGap",
    "BeeBrainSourceStatus",
    "BeeStackConfig",
    "BeehaveColonySummary",
    "BeliefState",
    "BodyState",
    "BodyTelemetry",
    "BrainState",
    "CalciumImagingProtocol",
    "CombGrid",
    "CombMetrics",
    "DataQualityCheck",
    "DanceVector",
    "DiagnosticRecord",
    "DigitalTwinReadinessReview",
    "DocumentationAudit",
    "FigureAudit",
    "EVIDENCE_AVAILABILITY_STATES",
    "EmpiricalAnatomyDataset",
    "EmpiricalBrainDataset",
    "EmpiricalCalciumDataset",
    "EmpiricalConfig",
    "EmpiricalEvidenceRecord",
    "EmpiricalOdorResponsePanel",
    "EmpiricalPanelStats",
    "EmpiricalTemplateBank",
    "EmpiricalWaggleFollowerDataset",
    "EvidenceTier",
    "FlyBodyBeeBackend",
    "FlyBodyContactMetrics",
    "FlyBodyConfig",
    "FlyBodyModificationPlan",
    "FlyBodySceneArtifact",
    "FlyBodySceneRenderConfig",
    "FollowerOrientationDiagnostics",
    "GeneratedReportAudit",
    "GlomerularResponseSummary",
    "HoneybeeCalibrationTarget",
    "ManuscriptEvidenceLink",
    "MethodsAnalysisReport",
    "ModuleIntegrityReport",
    "ModuleMethodScorecard",
    "ModuleMethodsPanel",
    "ModuleSynthesisPanel",
    "ModuleValidationPanel",
    "ModuleVisualizationPanel",
    "NeuropilAbbreviation",
    "NicheAdapterSummary",
    "Observation",
    "PheromoneField",
    "PolicyCandidate",
    "PolicySelectionDiagnostics",
    "ResearchConfig",
    "ResearchSuiteReport",
    "ResearchValidationRecord",
    "ScaleReadiness",
    "ScenarioSweepPanel",
    "SimulationResult",
    "SimulationState",
    "SparseCode",
    "StackContract",
    "StackIntegrityReview",
    "StackSynthesisReview",
    "SourceAudit",
    "SensitivitySweepResult",
    "TwinReadinessAxis",
    "TwinScale",
    "ValidationRecord",
    "VisualizationArtifactRecord",
    "VisualizationConfig",
    "WaggleDanceKinematics",
    "WaggleDecodingDiagnostics",
    "WaggleDanceVisualizationConfig",
    "WaggleFollowerSummary",
    "WaggleFollowerTrack",
    "action_to_flybody_action",
    "action_to_flybody_named_action",
    "action_schema",
    "allocate_tasks",
    "activity_summary_from_components",
    "all_checks_passed",
    "analyze_odor_panel",
    "antennal_vibration_from_movement",
    "atlas_download_record_from_asset",
    "atlas_download_records_from_dicts",
    "atlas_inventories_from_directory",
    "atlas_inventory_from_zip",
    "assemble_methods_analysis_report",
    "assemble_research_suite_report",
    "assemble_stack_synthesis_review",
    "assess_digital_twin_readiness",
    "audit_documentation",
    "audit_figures",
    "audit_sources",
    "adapter_smoke_rollout",
    "bee_body_calibration_summary",
    "bee_flight_cycle_action",
    "bee_walk_cycle_action",
    "bee_brain_data_completeness_panel",
    "beehave_colony_summary",
    "broadcast_dance",
    "build_flybody_modification_plan",
    "build_empirical_template_bank",
    "calcium_dataset_from_trial_array",
    "caste_prior",
    "comb_metrics",
    "config_from_mapping",
    "contract_matrix",
    "cost_of_transport",
    "dance_recruitment_diagnostics",
    "audit_generated_reports",
    "dataset_by_id",
    "datasets_for_module",
    "decode_waggle",
    "dominant_caste",
    "finalize_project_outputs",
    "documentation_audit_markdown",
    "generated_report_audit_markdown",
    "signposted_directories",
    "digital_twin_axis_catalog",
    "digital_twin_readiness_markdown",
    "empty_comb",
    "empirical_brain_datasets",
    "empirical_anatomy_datasets",
    "empirical_brain_profile",
    "extract_pandoc_citation_keys",
    "flybody_action_dim_from_env",
    "flybody_action_names_from_spec",
    "flybody_contact_report_markdown",
    "heading_estimate_deg",
    "hexagonal_packing_score",
    "honeybee_calibration_targets",
    "honeybee_standard_brain_assets",
    "integrity_review_markdown",
    "kc_class_counts",
    "load_neuropil_abbreviations",
    "manuscript_figure_index",
    "manuscript_figure_index_markdown",
    "metabolic_budget_j",
    "methods_analysis_markdown",
    "model_card",
    "module_coverage",
    "morphology_summary",
    "neuropil_abbreviations_from_html",
    "niche_adapter_summary",
    "observation_schema",
    "odor_panel_sparseness",
    "parse_paoli_matlab_payload",
    "parse_bibtex_entries",
    "parse_tabular_odor_response_rows",
    "pheromone_gradient",
    "policy_selection_diagnostics",
    "process_observation",
    "response_templates_from_calcium_dataset",
    "response_templates_from_odor_panel",
    "render_flybody_swarm_collision_scene",
    "render_flybody_waggle_scene",
    "render_flybody_long_waggle_scene",
    "research_report_markdown",
    "run_simulation",
    "run_sensitivity_sweeps",
    "stack_synthesis_markdown",
    "source_audit_markdown",
    "select_policy",
    "stack_contracts",
    "stack_integrity_review",
    "step_body",
    "summarize_anatomy",
    "summarize_calcium_trials",
    "summarize_antennal_movement_rows",
    "summarize_waggle_follower_rows",
    "task_allocation_snapshot",
    "template_alignment_matrix",
    "thermal_step",
    "validate_bee_body_plan_xml",
    "validate_calcium_dataset",
    "validate_config",
    "validate_diagnostic_payload",
    "validate_odor_panel",
    "validate_rendered_frames",
    "validate_stack_contracts",
    "waggle_dance_visualization_config",
    "waggle_decoding_diagnostics",
    "waggle_kinematics_from_config",
    "waggle_vibration_from_followers",
    "wing_power_mw",
    "write_modified_bee_body_plan",
    "write_prefixed_multi_bee_scene_xml",
    "zero_action",
    "zero_observation",
]

__all__ = tuple(sorted(_EXPORT_MODULES))

_CACHE: dict[str, Any] = {}


def resolve_export(name: str) -> Any:
    """Import and cache a public BeeStack symbol on first access."""
    if name in _CACHE:
        return _CACHE[name]
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module beestack has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    _CACHE[name] = value
    return value
