"""BeeBrain package: olfaction, sparse memory, CX navigation, vision, and waggle decoding."""

from ..utils import angular_distance_deg, circular_mean_deg
from .anatomy import (
    AtlasDownloadRecord,
    AtlasInventory,
    BeeBrainAnatomySummary,
    NeuropilAbbreviation,
    atlas_download_record_from_asset,
    atlas_download_records_from_dicts,
    atlas_inventories_from_directory,
    atlas_inventory_from_zip,
    load_neuropil_abbreviations,
    neuropil_abbreviations_from_html,
    summarize_anatomy,
)
from .central_complex import heading_estimate_deg, heading_ring
from .datasets import (
    BeeBrainAtlasAsset,
    EmpiricalAnatomyDataset,
    EmpiricalBrainDataset,
    dataset_by_id,
    datasets_for_module,
    empirical_anatomy_datasets,
    empirical_brain_datasets,
    honeybee_standard_brain_assets,
)
from .empirical import (
    BeeBrainEmpiricalProfile,
    CalciumImagingProtocol,
    GlomerularResponseSummary,
    default_calcium_protocol,
    empirical_alignment_score,
    empirical_brain_profile,
    empirical_odor_response_templates,
    negative_delta_f_over_f,
    summarize_calcium_trials,
)
from .empirical_analysis import (
    BeeBrainActivitySummary,
    BeeBrainDataCompletenessPanel,
    BeeBrainEndToEndReport,
    BeeBrainSourceGap,
    BeeBrainSourceStatus,
    DataQualityCheck,
    EmpiricalPanelStats,
    EmpiricalTemplateBank,
    activity_summary_from_components,
    all_checks_passed,
    analyze_odor_panel,
    bee_brain_data_completeness_panel,
    build_empirical_template_bank,
    template_alignment_matrix,
    validate_calcium_dataset,
    validate_odor_panel,
)
from .empirical_data import (
    AntennalMovementSummary,
    EmpiricalCalciumDataset,
    EmpiricalOdorResponsePanel,
    EmpiricalWaggleFollowerDataset,
    WaggleFollowerSummary,
    WaggleFollowerTrack,
    antennal_vibration_from_movement,
    calcium_dataset_from_trial_array,
    odor_panel_sparseness,
    parse_paoli_matlab_payload,
    parse_tabular_odor_response_rows,
    response_templates_from_calcium_dataset,
    response_templates_from_odor_panel,
    summarize_antennal_movement_rows,
    summarize_waggle_follower_rows,
    waggle_vibration_from_followers,
)
from .mushroom_body import associative_readout, kc_class_counts, kenyon_sparse_code
from .olfaction import glomerular_encode, lateral_inhibition
from .pipeline import process_observation
from .state import BrainState, DanceVector, SparseCode
from .vision import color_opponency, optic_flow_magnitude
from .waggle import (
    FollowerOrientationDiagnostics,
    WaggleDanceKinematics,
    WaggleDecodingDiagnostics,
    decode_waggle,
    johnston_event_detected,
    waggle_decoding_diagnostics,
    waggle_duration_from_distance,
    waggle_kinematics_from_config,
)

__all__ = [
    "BrainState",
    "AntennalMovementSummary",
    "AtlasDownloadRecord",
    "AtlasInventory",
    "BeeBrainActivitySummary",
    "BeeBrainAnatomySummary",
    "BeeBrainDataCompletenessPanel",
    "BeeBrainEmpiricalProfile",
    "BeeBrainEndToEndReport",
    "BeeBrainSourceGap",
    "BeeBrainSourceStatus",
    "BeeBrainAtlasAsset",
    "CalciumImagingProtocol",
    "DataQualityCheck",
    "DanceVector",
    "EmpiricalAnatomyDataset",
    "EmpiricalBrainDataset",
    "EmpiricalCalciumDataset",
    "EmpiricalOdorResponsePanel",
    "EmpiricalWaggleFollowerDataset",
    "EmpiricalPanelStats",
    "EmpiricalTemplateBank",
    "GlomerularResponseSummary",
    "FollowerOrientationDiagnostics",
    "NeuropilAbbreviation",
    "SparseCode",
    "WaggleDanceKinematics",
    "WaggleDecodingDiagnostics",
    "WaggleFollowerSummary",
    "WaggleFollowerTrack",
    "activity_summary_from_components",
    "all_checks_passed",
    "analyze_odor_panel",
    "antennal_vibration_from_movement",
    "angular_distance_deg",
    "atlas_download_record_from_asset",
    "atlas_download_records_from_dicts",
    "atlas_inventories_from_directory",
    "atlas_inventory_from_zip",
    "associative_readout",
    "circular_mean_deg",
    "color_opponency",
    "calcium_dataset_from_trial_array",
    "dataset_by_id",
    "datasets_for_module",
    "default_calcium_protocol",
    "decode_waggle",
    "empirical_alignment_score",
    "empirical_anatomy_datasets",
    "empirical_brain_datasets",
    "empirical_brain_profile",
    "empirical_odor_response_templates",
    "build_empirical_template_bank",
    "bee_brain_data_completeness_panel",
    "glomerular_encode",
    "heading_estimate_deg",
    "heading_ring",
    "honeybee_standard_brain_assets",
    "johnston_event_detected",
    "kc_class_counts",
    "kenyon_sparse_code",
    "lateral_inhibition",
    "load_neuropil_abbreviations",
    "negative_delta_f_over_f",
    "neuropil_abbreviations_from_html",
    "odor_panel_sparseness",
    "optic_flow_magnitude",
    "parse_paoli_matlab_payload",
    "parse_tabular_odor_response_rows",
    "process_observation",
    "response_templates_from_calcium_dataset",
    "response_templates_from_odor_panel",
    "summarize_anatomy",
    "summarize_calcium_trials",
    "summarize_antennal_movement_rows",
    "summarize_waggle_follower_rows",
    "template_alignment_matrix",
    "validate_calcium_dataset",
    "validate_odor_panel",
    "waggle_decoding_diagnostics",
    "waggle_vibration_from_followers",
    "waggle_duration_from_distance",
    "waggle_kinematics_from_config",
]
